### PR TITLE
Webrtc impl

### PR DESCRIPTION
**Pull request by wpears**
This was kinda buggy so I didn't PR it ^_~

Not buggy anymore...

Run `watchify main.js -o bundle.js` from `./client/js/`

Start the server with `node server.js` from `./server/`

Open many tabs at `localhost:1337`

**ENJOY**

### CODE REVIEW

**Comment by wpears** [comment]
Self-merging cause why not

**Comment by himedlooff** [comment]
Oh man, wanna check this out. I'll get to it on Tuesday when I'm near a
computer!

**Comment by contolini** [comment]
excited-michigan-state-band-girl-college-basketball-fan-gifs

**Comment by himedlooff** [comment]
Just played around, nice!

**Comment by wpears** [comment]
Yeah, it'll be interesting to see the response time on non-local p2p. Pretty awesome just between browser tabs. Haven't really done any performance testing, but as long as we don't blow ~12ms of JS per  animation frame it should be fine. Dunno what to expect re: sending data to WebRTC peers.. dunno if that's done in the JS thread or what.. but either way, it should probably scale up to the 10 concurrent users easy peasy.

**Comment by contolini** [comment]
I'll try and throw it on a server tonight to check non local latency. And
then we should probably draft gameplay specifications.

On Monday, September 7, 2015, Wyatt Pearsall notifications@github.com
wrote:

> Yeah, it'll be interesting to see the response time on non-local p2p.
> Pretty awesome just between browser tabs. Haven't really done any
> performance testing, but as long as we don't blow ~12ms of JS per animation
> frame it should be fine. Dunno what to expect re: sending data to WebRTC
> peers.. dunno if that's done in the JS thread or what.. but either way, it
> should probably scale up to the 10 concurrent users easy peasy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/forty-eight/assassin-king/pull/1#issuecomment-138399917
> .

## 

Chris

**Comment by contolini** [comment]
So snappy https://assassin-king-contolini.c9.io:8080/

**Pull request merged**
